import { IAICapability, HarnessContext } from '../interfaces';

export interface CodeGenInput {
  target: 'component' | 'route' | 'service' | 'model';
  name: string;
  description?: string;
  options?: Record<string, any>;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface CodeGenOutput {
  success: boolean;
  files: GeneratedFile[];
  summary: string;
}

export class CodeGenerationCapability implements IAICapability<CodeGenInput, CodeGenOutput> {
  readonly id = 'code-generation';
  readonly name = 'Stack-Aware Code Generation';
  readonly description = 'Scaffolds components, endpoints, and services tailored to the detected project stack.';

  async execute(input: CodeGenInput, context: HarnessContext): Promise<CodeGenOutput> {
    const profile = await context.indexer.getProjectProfile(context.projectRoot);
    const files: GeneratedFile[] = [];

    const baseName = input.name.charAt(0).toUpperCase() + input.name.slice(1);
    const kebabName = input.name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

    if (input.target === 'component') {
      const isReact = profile.frontend?.framework === 'react' || profile.frontend?.framework === 'next.js';
      const ext = isReact ? 'tsx' : 'vue';
      const content = `import React, { useState } from 'react';

export interface ${baseName}Props {
  title?: string;
  className?: string;
}

export const ${baseName}: React.FC<${baseName}Props> = ({ title = '${baseName}', className = '' }) => {
  const [active, setActive] = useState(false);

  return (
    <div className={\`p-4 rounded-lg border border-gray-800 bg-gray-900 \${className}\`}>
      <h3 className="text-lg font-semibold text-white">{title}</h3>
      <p className="text-xs text-gray-400 mt-1">Generated by Codex AI Harness</p>
      <button
        onClick={() => setActive(!active)}
        className="mt-3 px-3 py-1.5 text-xs font-medium bg-blue-600 hover:bg-blue-500 text-white rounded transition-colors"
      >
        {active ? 'Active' : 'Toggle State'}
      </button>
    </div>
  );
};

export default ${baseName};
`;
      files.push({
        path: `frontend/src/components/${baseName}.${ext}`,
        content,
      });
    } else if (input.target === 'route') {
      const content = `import { Router, Request, Response } from 'express';

export const ${kebabName}Router = Router();

// GET /api/${kebabName}
${kebabName}Router.get('/', (req: Request, res: Response) => {
  res.json({
    success: true,
    service: '${input.name}',
    status: 'operational',
    timestamp: new Date().toISOString(),
  });
});

// POST /api/${kebabName}
${kebabName}Router.post('/', (req: Request, res: Response) => {
  const data = req.body;
  res.status(201).json({
    success: true,
    message: 'Entity created successfully',
    data,
  });
});
`;
      files.push({
        path: `backend/src/api/handlers/${baseName}Handler.ts`,
        content,
      });
    } else if (input.target === 'service') {
      const content = `export interface ${baseName}Result {
  success: boolean;
  timestamp: string;
  data?: any;
}

export class ${baseName}Service {
  async performOperation(payload: any): Promise<${baseName}Result> {
    return {
      success: true,
      timestamp: new Date().toISOString(),
      data: payload,
    };
  }
}
`;
      files.push({
        path: `backend/src/services/${baseName}Service.ts`,
        content,
      });
    }

    return {
      success: true,
      files,
      summary: `Generated ${files.length} files tailored for ${profile.language} and ${profile.frontend?.framework || 'backend'} stack.`,
    };
  }
}
